### ISSUE TITLE
Bootstrap 4 with table inside 

### ISSUE THREAD

**Issue by ianbroad** [DataTables/FixedHeader#100]
Example: https://jsfiddle.net/9evb8owd/

If you make the example window narrow, and then scroll left or right to view the table, the fixed headers do not move with the table. How do I fix this?

**Comment by ianbroad** [comment]
Example: https://jsfiddle.net/9evb8owd/

If you make the example window narrow, and then scroll left or right to view the table, the fixed headers do not move with the table. How do I fix this?

**Comment by DataTables** [comment]
This has [just been discussed](https://datatables.net/forums/discussion/62081/floating-fixedheader-doesnt-scroll-horizontally#latest) in the last few days in the DataTables forums.

Going to close this thread, so the information is just in a single location.
