### ISSUE TITLE
"oOffset" Documentation

### ISSUE THREAD

**Issue by dummey** [DataTables/FixedHeader#14]
This settings allows for an offset from the top of the page to be used to start the fixed header. This is useful if the page already has another fixed header of some sort. Unfortunately, this useful feature, is not documented and was only discovered by random chance.

**Comment by DataTables** [comment]
The `fixedHeader.headerOffset` and `fixedHeader.footerOffset` parameters are correctly documented as of v3: http://datatables.net/extensions/fixedheader/examples/options/offset.html
