### ISSUE TITLE
Tab + Ajax Proposed Quick Fix. 

### ISSUE THREAD

**Issue by timothymarois** [DataTables/FixedHeader#19]
I have wrote a small quick patch for tabbed content. 

At the moment, fixedheader appends to the body, which is not good when dealing with external tables loading in ajax and using tabs at the same time. Each tab loads a different table, and fixed header is one class without an id. so here is what I proposed. 

fixedHeader.js line 329 I have added
jQuery(nCTable).parent().attr( "clone-id", jQuery(s.nTable).attr('id'));

This adds clone-id to the fixedheader div so that each table has its own identifier. 

On the application, I've added something like this to move fixedheader inside the proper div

$('div[clone-id="'+a.tabId+'"]').each(function() {
        $(this).appendTo("#"+a.tabId);
 });

(of course variables are different, but you use a dynamic tab system, so that you place tabid within each one, and it will make sure they are properly placed inside each tab. There's a cleaner way to do this, I just wrote this up for my app. 

Without this fix, when you move from tab to tab, it keeps the existing fixedheader div from each tab still active, making the page look cluttered with the wrong headers. 

I do know you can also use 
oFH.fnUpdate(); to update the fixedheader, but dynamic structure like this, it does not work. I've tried many ways to make that work. The best thing for fixedHeader is place the div under the table and add the correct identifier. Otherwise you are left with cloned divs in the footer that have no real direction.

**Comment by DataTables** [comment]
FixedHeader has `fixedHeader.enable()` and `fixedHeader.disable()` methods now (as of v3). It attempts to do some automatic detection of the table - if it is hidden then the header won't be enabled by default. I think that's probably as far as we can take it without proper DOM mutation listeners.
