### ISSUE TITLE
Misalignment IE9> when using bordered cells.

### ISSUE THREAD

**Issue by ravb** [DataTables/FixedHeader#24]
I'm using datatables for a table with 100% width. Works reasonably fine with FF, Webkit and IE8 (oddly enough), but the cells' borders in the cloned header are misaligned with the rest of the table in IE9 and onward. 

![misalignment-table](https://cloud.githubusercontent.com/assets/4758964/2539517/19c8bb12-b5c9-11e3-80b6-83ceb4eb2f9f.png)

I ran into a similar problem with a setup concerning a static table before and had already created a sloppy, base fix for this myself using some simple jquery, but I'd prefer to use datatables (and a plugin for the fixed header) for my application.

In the end it all came down to IE's handling of subpixels, so I ended up doing some sort of browser check (those that can handle getComputedStyle and those that can't) and set up 2 basic calculations for each scenario; one using the getComputedStyle-method and the other using the basic (more widely accepted) getBoundingClientRect-method.

Are you planning to implement such a fix in the foreseeable future? (I'd do it myself, but my JS-programming isn't that great, tbh)

**Comment by joe-meyer** [comment]
I think I'm seeing the same issue. I see it in IE8,9,10. 

Here's a fiddle: http://jsfiddle.net/50x1m4bt/6/

And a picture (you may have to shrink that frame's width a bit to get it to show up, seems like the smaller the window's width the farther off it gets):
![image](https://cloud.githubusercontent.com/assets/1292766/10085906/867a47bc-62d9-11e5-860c-e91a4e843703.png)

**Comment by joe-meyer** [comment]
Also, the table cells don't even have to be bordered, but it certainly makes it easier to see.

**Comment by DataTables** [comment]
Fantastic - thanks for the test case - this is it with the nightly version of FixedHeader: http://jsfiddle.net/50x1m4bt/7/ and the error is still present.

I'll try to make some time to look into it next week. It looks like it will be particularly horrible to fix - the floating header has a width of 998px applied (for my specific system, it will change between machines) using the `style.width` property but IE is rendering it as 819px wide :-/

**Comment by joe-meyer** [comment]
I found one solution to the problem.... http://stackoverflow.com/a/14765961/1535329

I tried out just wrapping my text in a div inside of the `th` tag and assigning the width to that and it seemed to clear up the issue in IE. I'm a bit out of my element with the fixedHeader code yet so if someone else wants to take a stab at implementing it that would be swell.

Resulting th html could look something like this:

```html
<th tabindex="0" class="text-nowrap" aria-controls="DataTables_Table_0" aria-label="Part: activate to sort column ascending" rowspan="1" colspan="1">
    <div style="width: 118px;">
        Part
    </div>
</th>
```

**Comment by joe-meyer** [comment]
Or as the comments suggest one could simply use `min-width` instead of `width`. It seems to keep wrapping ok (at least in the case of IE).

**Comment by DataTables** [comment]
Good info that - thanks! Setting min-width and width might be the way to go here.
