### ISSUE TITLE
fnUpdate() not working with ColVis

### ISSUE THREAD

**Issue by tudor-sv** [DataTables/FixedHeader#26]
I've encountered a bug when using FixedHeader(2.1.0) with ColVis.
After toggling columns via ColVis, the table rows get updated, but the columns in the fixed header don't get updated.
Calling fnUpdate /* FixedHeader */ inside fnStateChange /* ColVis */ didn't work.
I've made the fix for my use case, but I'm not sure it doesn't break the functionality for other use cases.
<pre>
Basicaly, I turned this:

/*
	 * Function: fnUpdate
	 * Purpose:  Update the positioning and copies of the fixed elements
	 * Returns:  -
	 * Inputs:   -
	 */
	this.fnUpdate = function () {
		this._fnUpdateClones();
		this._fnUpdatePositions();
	};

Into this:

/*
	 * Function: fnUpdate
	 * Purpose:  Update the positioning and copies of the fixed elements
	 * Returns:  -
	 * Inputs:   -
	 */
	this.fnUpdate = function (prm) {
		this._fnUpdateClones(prm);
		this._fnUpdatePositions();
	};

And in my implementation:

// fixed header
    var tableFH = new $.fn.dataTable.FixedHeader( myDataTable );

// updating the fixed header each time we toggle a column via ColVis
myTable
  .dataTable( {
        ... ,
        'colVis' : {
          ... ,
          'fnStateChange' : function(col, vis) {
            tableFH.fnUpdate(true);
          }
        },
        ...
  }
</pre>

I'm also new to Git and GitHub. Might make newbie mistakes :)
Awesome plug-ins, I'm happy to contribute !

**Comment by DataTables** [comment]
Wow - long term bug this one - sorry! FixedHeader and the column visibility component of the newer Buttons extension works well now - example committed here: 36cb6d01f6a7909bd3662d27771fdf5c257cd039
