### ISSUE TITLE
DataTables with column widths defined in % loose the % and don't resize correctly 

### ISSUE THREAD

**Issue by xmojmr** [DataTables/FixedHeader#33]
This fiddle → <http://jsfiddle.net/xmojmr/bp4hz/4/> shows that although column widths are defined in % (by using columns.width) then on-screen width changes to pixels. e.g. 20% becomes 20px (look at **TH** cells)

This fiddle → <http://jsfiddle.net/xmojmr/6EdUF/2/> shows that pull request #34 fixes it. **TH** cell width remains % even after window is resized

**Comment by DataTables** [comment]
Discussion continues in #34.
