### ISSUE TITLE
Events are ok with 1 input but fails with 2 or more

### ISSUE THREAD

**Issue by SneakyBobito** [DataTables/FixedHeader#39]
When you have an input in the ``thead>tr>th`` and when this input has some events. Then the event are working with the cloned thead.

Now if you have more than 1 input in one ``th`` then the input events does not work anymore.

**Comment by SneakyBobito** [comment]
Close because it will probably never be fixed

**Comment by DataTables** [comment]
Sorry I missed this at the time. If you coudl like to a test case showing the issue that would be useful.
