### ISSUE TITLE
Position mismatch when the leftmost column is fixed

### ISSUE THREAD

**Issue by orangeclk** [DataTables/FixedHeader#41]
I made a table with Chinese content. When I tried to fix the left most column, the vertical position of left most column became higher than the rest columns. So the table was not aligned.

My Environment:
JQuery 2.1.1
DataTables 1.10.1
DataTables FixedHeader 2.1.1

**Comment by latipovsharif** [comment]
Hi, is there any workaround to fix this issue? or any plans when this bug will fixed. Thanks!

**Comment by DataTables** [comment]
Closing this as part of a tidy up. FixedHeader no longer supports fixing columns in place.
