### ISSUE TITLE
Append filters to header columns (yadcf)

### ISSUE THREAD

**Issue by vedmack** [DataTables/FixedHeader#47]
I was wondering what is the best way to append my yadcf filters to the `th` of the columns,

Right now I'm using the `oTable._fnGetUniqueThs()` to get the `th` to which I append filters, but with FixedHeader it doesn't play well, any suggestions on how I should handle it?

Here is my [test case](https://dl.dropboxusercontent.com/u/55621125/yadcf/war14/DOM_source_chosen.html)

https://github.com/vedmack/yadcf/issues/157

**Comment by DataTables** [comment]
To be honest there isn't a good why of handling this at the moment. FixedHeader needs a big upgrade in this regard. There are also a number of complications when you consider that the FixedHeader can reclone the original cells under certain circumstances, destroying any inputs and user data already present.

At this time, FixedHeader just isn't suitable for this kind of thing. Sorry!

**Comment by DataTables** [comment]
Things have chanced this we originally discussed this. As of v3, FixedHeader doesn't display a clone but rather the original element - so this should now work without any modification.

**Comment by vedmack** [comment]
Great news :)

I jsut tried it on my [showcase page](http://yadcf-showcase.appspot.com/DOM_Ajax_Multiple_1.10.html) , but it doesn't seems to work at all. You can take a look ath the [dom_ajax_multiple_1.10_example.js](http://yadcf-showcase.appspot.com/resources/js/dom_ajax_multiple_1.10_example.js) (or even better from dev tools) , I also noticing that something does happen while scrolling (it can be noticed in the elements tab of the chrome dev tools) but in the end on the UI nothing happens.

**Comment by DataTables** [comment]
The page isn't including the FixedHeader CSS, which is required in v3. I think that should resolve the issue.

**Comment by vedmack** [comment]
Ohh, my bad. its working now :)

Say did the *FixedColumn* got an upgrade as the *FixedHeader*? If not, is it planned?

**Comment by DataTables** [comment]
FixedColumns unfortunately has to take a clone of the element since it needs to float on the left or right. I haven't found a way around that yet, so currently no, there is no planned change for that.
