### ISSUE TITLE
FixedHeader breaks when any ancestor element of the grid is positioned absolute or relative or fixed.

### ISSUE THREAD

**Issue by mendeza** [DataTables/FixedHeader#50]
One of the parent elements of this grid has position: absolute.

![datatablefixedheader](https://cloud.githubusercontent.com/assets/1161280/6968279/87ab7db6-d933-11e4-8c30-2a84423b510c.png)

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please?

**Comment by DataTables** [comment]
It appears to work in this little example: http://live.datatables.net/zalomipa/1/edit .

Going to close, but if this is still an issue please reopen with a test case.
