### ISSUE TITLE
Fixed Header Scrolling problem

### ISSUE THREAD

**Issue by djangosdk** [DataTables/FixedHeader#51]
Hi,
I am using fixed header extension but it is not working correctly with horizontal scroll.
Is anyone having issue with both ?

**Comment by DataTables** [comment]
Seems to work just fine here: http://datatables.net/extensions/fixedheader/ .

Please link to a test case showing the issue.

**Comment by djangosdk** [comment]
yes but there is no horizontal scroll in this example.

**Comment by DataTables** [comment]
Can you please link to a test case showing the issue? Are you using the `scrollX` option in DataTables? FixedHeader is not compatible with that option and it should show an error stating that fact.

**Comment by djangosdk** [comment]
I will prepare example today later on jsfiddle and getback at you.

**Comment by LucaDanieli** [comment]
Hello, sorry. May I ask if you solved this issue and how, as I'm having some troubles?

**Comment by DataTables** [comment]
Actually yes, this one should be fixed. I forgot to update it. If it isn't working for you, please link to a test case as I asked above.

**Comment by DataTables** [comment]
Closing as fixed. This was addressed in FixedHeader 3.0.1.
