### ISSUE TITLE
Header is display on top if the datatable is in a hidden container

### ISSUE THREAD

**Issue by pc-jedi** [DataTables/FixedHeader#55]
Hey,

the header is displayed in the top, if the table is inside a hidden cotainer.

Example:
[JSFiddle](http://jsfiddle.net/o5pmb377/)

**Comment by DataTables** [comment]
You need to use the fnEnable and fnDisable API methods of FixedHeader - it doesn't know when the table has been shown or hidden: https://datatables.net/extensions/fixedheader/api .
