### ISSUE TITLE
fixedHeader css

### ISSUE THREAD

**Issue by bolemeus** [DataTables/FixedHeader#56]
In the fixedHeader css the following rule is applied to the fixed header.

```
div.FixedHeader_Cloned th,
div.FixedHeader_Cloned td {
	background-color: white !important;
}
```

I get that the background should be set, but enforcing the color white with the !important modifier prevents the application of another background color, unless you reorder the list of css files, and apply the !important modifier to your own rule as well, and that really shouldn't be necessary.

Maybe I'm missing the reason here behind the !important modifier, but I've removed it for my usecase (column highlighting + fixedHeader), and it works fine. For other usecases (ie. tables in different colors) thesame problem arises.

**Comment by DataTables** [comment]
[Already done on the 3 branch](https://github.com/DataTables/FixedHeader/blob/3/css/fixedHeader.dataTables.scss). I'll be merging that down to master as soon as I've written the documentation for the new version.
