### ISSUE TITLE
It does not work with autoWidth

### ISSUE THREAD

**Issue by mitar** [DataTables/FixedHeader#57]
It does not work with autoWidth (and server side loading). The header cells' widths does not adapt to the widths of the data columns.

**Comment by smartcorestudio** [comment]
The same thing is with local data too
![2015-08-16 15_45_54- 100](https://cloud.githubusercontent.com/assets/2891792/9293283/e3155fd6-442d-11e5-869d-d70d61b7c6a4.png)

It works better but still not perfect without autoWidth (there are some issues with window resizing)

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please.

**Comment by smartcorestudio** [comment]
http://jsfiddle.net/smartcore/nuamc2fn/6/

**Comment by smartcorestudio** [comment]
Everything works OK on my page if I use external plugin for fixing header: http://mkoryak.github.io/floatThead/datatables/
I just wanted to use native solution provided by DataTables developer...

**Comment by DataTables** [comment]
Great thanks. I'll look at it this week. Probably Tesuday (Monday looks busy!)

**Comment by DataTables** [comment]
Updated example with the FixedHeader nightly: http://jsfiddle.net/nuamc2fn/7/ .

Thanks for letting me know about this issue!

**Comment by mitar** [comment]
Hm, I updated to latest (`master` branch) version of this plugin, but now nothing happens. Header does not even move anymore when scrolling. Is it possible that this is because I am using server side processing?

**Comment by DataTables** [comment]
Can you link to a page showing the issue please

**Comment by mitar** [comment]
Is there a jsFiddle which uses server side processing? I could use it to make a reproduction.

**Comment by DataTables** [comment]
http://live.datatables.net/sesohidi/1/edit

**Comment by mitar** [comment]
Sorry, it works. I just had to correctly update the CSS.
