### ISSUE TITLE
doesn't work correctly on Chrome for Android 

### ISSUE THREAD

**Issue by kshipp** [DataTables/FixedHeader#59]
When viewing on a Samsung phone (uses Chrome for Android), the floating header floats incorrectly - both vertically and horizontally.  If you change the orientation of the phone to horizontal, the floating works correctly.
When in portrait mode, the header floats far too low and if you attempt to scroll horizontally, the floating header doesn't scroll horizontally.  All kinds of issues....

**Comment by DataTables** [comment]
Could you possibly try with the 3.0.0 release of FixedHeader please? [Example](https://datatables.net/extensions/fixedheader/examples/options/simple.html). I don't have an Android device to test with at the moment.

**Comment by InfinityGone** [comment]
Gave 3.0.0 a quick spin with my device.  Orientation doesn't seem to have any impact.

**Header**
It is in the correct location vertically with the 3 browsers I have (Chrome, Firefox, HTC).  However, it does not respond to horizontal scrolling in Firefox and HTC.

Chrome works most of the time with horizontal scroll, however the header occasionally gets stuck scrolled to the right (excess left padding/margin?).  I can't quite nail down what I do to cause it, and it fixes itself after a few scrolls...  Might be related to the address bar coming in.

**Footer**
Works in Firefox with the same horizontal scroll issue. Does not appear at all in Chrome or HTC.

**Comment by DataTables** [comment]
Horizontal scroll is most certainly a bug - an oversight on my part. Thanks for pointing it out.

For the rest, I'll try to get ahold of an Android device.

**Comment by gsarrica** [comment]
@DataTables You can make this happen right in Chrome if you open Developer Tools and Select the Nexus 6P as a device.  [Screenshot](http://i.imgur.com/cpUnFcr.png) If you scroll back up sometimes the header will show back up.

**Comment by DataTables** [comment]
Thanks! I'll try to take a look in the next week or two after I've polished off some other work.

**Comment by amavarick** [comment]
I recently installed this and it works great on pc.  I'm having the same issue on my Android with Chrome though...  any workaround?

**Comment by DataTables** [comment]
It appears that you need to have `user-scaleable=no` in your meta tags for position:fixed to work in Android Chrome. I've updated my examples to this and I'm going to add a test for this for a new debugger I'm working on.
