### ISSUE TITLE
Header width gets randomized

### ISSUE THREAD

**Issue by MarioLipinski** [DataTables/FixedHeader#60]
The header columns get resized when fixed header is used.... please see the fiddle for demo.

https://jsfiddle.net/fj2a9e1x/

**Comment by runofthemill** [comment]
+1

**Comment by DataTables** [comment]
This is a duplicate of #57 which I've just committed a fix for. [Update of your example](https://jsfiddle.net/fj2a9e1x/4/) with the fix applied in the nightly version.
