### ISSUE TITLE
CDN - 404 for CSS file 

### ISSUE THREAD

**Issue by runofthemill** [DataTables/FixedHeader#61]
FYI -

![screen shot 2015-08-18 at 6 02 53 pm](https://cloud.githubusercontent.com/assets/8418440/9343964/6310dbd8-45d3-11e5-9c7d-5636e8a0bbd8.png)

**Comment by DataTables** [comment]
The file is now called `fixedHeader.dataTables.css` ([link](http://cdn.datatables.net/fixedheader/3.0.0/css/fixedHeader.dataTables.css)).

The files available on the CDN for FixedHeader 3.0.0 a [noted here](http://cdn.datatables.net/fixedheader/3.0.0/#Files).

**Comment by runofthemill** [comment]
Looks like the [download page](http://datatables.net/download/release#FixedHeader) is still linking to the previous file name.

**Comment by DataTables** [comment]
Darn. Thanks. I'll push an update out shortly.
