### ISSUE TITLE
Adjust function doesn't exists (update)

### ISSUE THREAD

**Issue by tomours** [DataTables/FixedHeader#66]
Hi, I've had a little issue while installing new version (3) of fixedheader.
As I was trying, to use "adjust" function, which is referenced in the documentation (see http://datatables.net/reference/api/#fixedheader), my browser kept saying me "this function is not defined".
It seems that the function is named "update" in the code, and not "adjust".

**Comment by DataTables** [comment]
It is [definitely called `fixedHeader.adjust()`](https://github.com/DataTables/FixedHeader/blob/master/js/dataTables.fixedHeader.js#L500).

Can you link to a test case showing the issue please.

**Comment by tomours** [comment]
Well, maybe I misunderstood the way it's supposed to work.
What I did :
> my_fixed_header_name = new $.fn.dataTable.FixedHeader(my_table_name, {some options});
and, at some other place I tried :
> tableau_fixed_header.adjust();
that didn't work.
What worked for me :
> tableau_fixed_header.update();

**Comment by DataTables** [comment]
I see - you are using the FixedHeader "internal" API. Although that is possible, I would recommend that you use the API that is exposed via the DataTables API, as shown in the documentation.
