### ISSUE TITLE
CDN link for CSS does not work

### ISSUE THREAD

**Issue by mitar** [DataTables/FixedHeader#67]
Here:

https://cdn.datatables.net/

The link for CSS does not work:

https://cdn.datatables.net/fixedheader/3.0.0/css/dataTables.fixedHeader.min.css

Because it is:

https://cdn.datatables.net/fixedheader/3.0.0/css/fixedHeader.dataTables.css
https://cdn.datatables.net/fixedheader/3.0.0/css/fixedHeader.dataTables.min.css

**Comment by DataTables** [comment]
Thanks for letting me know about that. Fix deployed now.
