### ISSUE TITLE
Support for form elements in header/footer

### ISSUE THREAD

**Issue by MarioLipinski** [DataTables/FixedHeader#68]
Hi,

it looks that form elements in fixed header/footer are not supported since the tables for header/footer are placed in the DOM outside of the table (which, in my case, is surrounded by form tags). Would it be possible to keep the header/footer inside the original table to keep forms working?

**Comment by DataTables** [comment]
The elements are supported, but they are placed outside of the form, which I guess is the issue you are having here? It might be possible to keep the elements in the table, but I'm not sure how - the positioning of the elements as it is currently implemented requires them to be moved outside of the table.

You could disable the fixed header immediately prior to the submission which would allow it to work as expected.

**Comment by MarioLipinski** [comment]
That's exactly the issue i am having here.

How to disable FixedHeader? Hiding the whole table and updating the complete header seems a bit over the top (https://www.datatables.net/extensions/fixedheader/examples/options/enable-disable.html).

**Comment by DataTables** [comment]
I must admit, I had thought there was a `fixedHeader.enable()` and `fixedHeader.disable()` method, but they aren't in the code - I must had missed them. They are what I would recommend - I'll put them in and comment back here when done.

**Comment by DataTables** [comment]
I've added them in 5dec307e9f8d9d and I'll just rebuild the nightly now.
