### ISSUE TITLE
Make compatible with FixedColumns

### ISSUE THREAD

**Issue by DataTables** [DataTables/FixedHeader#7]
Currently FixedHeader doesn't work with FixedColumns. Its probably not particularly easy to make it compatible given the structure of the two programs at the moment, but it would be good if they could play together (acknowledging possible performance concerns with lots of cloned elements on the page).

**Comment by sokai** [comment]
Think it's done: https://datatables.net/extensions/fixedheader/examples/integration/fixedcolumns.html 👍🏼

**Comment by AllanJard** [comment]
Certainly is! Thanks for noting this.
