### ISSUE TITLE
FixedHeader does not work with Buttons

### ISSUE THREAD

**Issue by gesior** [DataTables/FixedHeader#71]
I've installed FixedHeader 3.0.0 and it worked very good (better then other 'table floating header' codes).
After I added Buttons plugin ( https://github.com/DataTables/Buttons - version 1.03), it stopped working.

Thing I've noticed is that new **&lt;table&gt;** element (floating table head) does not appear in DOM.

**Comment by DataTables** [comment]
Could you post support requests in the DataTables forums. Please also ensure that you link to a running test case showing the issue so it can be debugged.

**Comment by DataTables** [comment]
Going to close for now after no feedback here. If this is still an issue please open a forum thread and link to it from here so I can keep track of things :-)
