### ISSUE TITLE
datatables header fixed, in horizontal scroll, yet not supported? 

### ISSUE THREAD

**Issue by ijunaid8989** [DataTables/FixedHeader#74]
I have been searching around and all what i found that old versions dont support that. 

Is there any update on this?

**Comment by DataTables** [comment]
[Seems to work for me](http://live.datatables.net/palajori/1/edit) although perhaps I have misunderstood your question. Please link to a test case showing the issue.

**Comment by ijunaidfarooq** [comment]
what you are showing me is for Vertical scroll not for horizontal scrolling,   
![image](https://cloud.githubusercontent.com/assets/13561999/11837727/938c95a6-a404-11e5-9ebb-168c3da1bf07.png)

I hope you will understand it now.

**Comment by DataTables** [comment]
Oh I see - you mean you have enabled `scrollX` in DataTables? If so, then yes, FixedHeader is not supported with `scrollX` or `scrollY`.

**Comment by ijunaidfarooq** [comment]
Okay :)

**Comment by ninjaonsafari** [comment]
why have you closed this issue? this should be implemented...

**Comment by ijunaid8088** [comment]
@ninjaonsafari Yeah I thought so as well.. But no body did anything yet.. 

Opening the issue,, may be I will work on it by myself..

**Comment by DataTables** [comment]
Yup - this is something that should and will be implemented once I get some time to work on it.

**Comment by tmendesilva** [comment]
Any news about this issue? tnks

**Comment by DataTables** [comment]
No sorry. FixedHeader support for `scrollX` / `scrollY` is not a feature I'm like to get time to implement in the near future.

**Comment by DataTables** [comment]
Closing as a duplicate of #7.
