### ISSUE TITLE
Position the header lower than the top of the page

### ISSUE THREAD

**Issue by peterbenoit** [DataTables/FixedHeader#78]
I'm trying to use this in WordPress, which has the top nav bar, which the Datatables header appears underneath when I use this. Is there a way I can position it say 50px from the top?

**Comment by DataTables** [comment]
* [Example](https://datatables.net/extensions/fixedheader/examples/options/offset.html)
* [Documentation](https://datatables.net/reference/option/fixedHeader.headerOffset)
