### ISSUE TITLE
FixedHeader on DataTables which has columns width defined doesn't work

### ISSUE THREAD

**Issue by bijoyanupam** [DataTables/FixedHeader#81]
Not sure if I am doing soemthing wrong, or not. After lot of searching around, couldn't find working solution to the problem I am facing. Not sure if FixedHeader library is non-compatible or it is not handled properly. In any case, please do help.

When I scroll down, the column width shifts a little. And when I scroll back top to initial position, the columns width are all gone, and it looks like it defaults to autowidth. I am using columns width for some of the columns (Ref: [https://datatables.net/reference/option/columns.width])

I tried using `autoWidth: false` as mentioned in some of the related discussions, but it doesn't work. The width gets reset, when we scroll the page. Is it something which i miss?

Please check the fiddle link: https://jsfiddle.net/bijoyanupam/9787cfhy/

**Comment by DataTables** [comment]
Looks like you've reported it [in the forum as well](https://www.datatables.net/forums/discussion/36910/). Rather than duplicating work, let just keep it in the forum like the new issue text requests.
