### ISSUE TITLE
FixedHeader broken in IE11 with column searching

### ISSUE THREAD

**Issue by wkrick** [DataTables/FixedHeader#84]
Here's a live test case that demonstrates the problem when viewed in IE11...

http://files.3feetunder.com/datatable_test.html

When you move the search into the floating header, it works fine in Chrome and Firefox, but is completely broken in IE11.  There's some kind of focus problem, and once you search and then clear your search, the FixedHeader no longer floats as it should.

**Comment by DataTables** [comment]
Looks like I can only type a single character at a time in IE11. Thanks for letting me know about this. I'll try to make time to look into it later this week.

**Comment by DataTables** [comment]
This has cropped up in [a discussion in the forums as well](https://www.datatables.net/forums/discussion/37905).

**Comment by wkrick** [comment]
Yep.  I posted there initially, and I thought I had a workaround, but it doesn't really work correctly and actually breaks things in new and interesting ways in Edge...

https://datatables.net//forums/discussion/37052

**Comment by wkrick** [comment]
Any leads on what might be causing this bug?

**Comment by DataTables** [comment]
Not yet sorry - I haven't had a chance to look into it yet.

**Comment by davidmcglynn** [comment]
Also looking for a solution to this one, any idea when/if this will be addressed?

**Comment by DataTables** [comment]
Sorry about the standard open source cop out, but pull requests welcome. I've not had a chance to look into it yet - keep getting tied up with other stuff!

**Comment by davidmcglynn** [comment]
No apology necessary - I almost felt bad posting that.. If I were a
half-decent programmer I'd take you up on it. I fear I'd mess it up worse.
Thanks for all that you do, Allan!

**Comment by DataTables** [comment]
Just spent a little over an hour mucking around with IE on this and I'm afraid I feel like I'm fruther from an answer than when I started.

Even if I manage to keep the element in focus, IE appears to ignore every second key stroke. That isn't due to extra event listeners - IE just appears not to trigger the event at all. No answer yet I'm afraid.
