### ISSUE TITLE
header changes size on scroll and is no longer x-scrollable after library-update

### ISSUE THREAD

**Issue by McRadio** [DataTables/FixedHeader#86]
hello,

i wanted to update the datatables-library from version 1.10.2 to 1.10.12. .
At one datatable we are displaying a huge amount of information(about 29 columns up to 8000 rows).
At this datatable i now have the same issue mentioned at https://github.com/DataTables/FixedHeader/issues/64. 

So fixedHeader is resizing the th-tags, it is no more scrollable in x-direction, and the fixedHeader is not bordered (to the right) by its surrounding div. 

I tried to reproduce the error in an jsfiddle but there it worked properly, i also tried to remove all possible disturbing other js/jquery-functions used in the project, but it still does not work.

**Comment by DataTables** [comment]
If you link to a test page showing the issue I'd be happy to have a look at it.

**Comment by McRadio** [comment]
Finally, i could reproduce the fixedHeader Error in a JS-Fiddle: https://jsfiddle.net/McRadio/m0xfdef5/90/

**Comment by McRadio** [comment]
Ok, i realized that fixedHeader and Scroller are not compatible, but why is it not possible to make ScrollX and the fixedHeader compatible? 

Solved the Problem by disclaiming fixedHeader and taking scrollX and scrollY. 
btw: Sorry for my English.

**Comment by DataTables** [comment]
When scrolling is enabled, DataTables has to split the table into a header and body (and footer if there is one) in separate tables. Currently FixedHeader isn't programmed to cope with that. It is something that I would like to add in future.

**Comment by LeonardoGentile** [comment]
ping

**Comment by rakibulhaq** [comment]
ping
