### ISSUE TITLE
Clonning header duplicates elements `id`s

### ISSUE THREAD

**Issue by kmmbvnr** [DataTables/FixedHeader#88]
If the table header contains an element with `id` attribute, the FixedHeader would duplicate it in the table header clone. This breaks other js code relying on that id's.

I have this issue with a checkbox in a table header.

```diff
- itemDom.placeholder = itemElement.clone( false );
+ var clonedElement = itemElement.clone( false )
+ clonedElement.find("*[id]").attr('id',function(i,id){ return id+"_cloned"; });
+ clonedElement.find("*[for]").attr('for',function(i,id){ return id+"_cloned"; });
+ itemDom.placeholder  = clonedElement;
``

**Comment by DataTables** [comment]
Thanks for this! Rather than modifying the id, I've just removed it as I'm not sure anyone would find the cloned id easily. I've also not removed the `for` attribute - as far as I am aware they don't need to be unique so I don't think they would cause any issues (I could be wrong!).
