### ISSUE TITLE
Fixed columns and header for dynamic data

### ISSUE THREAD

**Issue by deepabagewadi** [DataTables/FixedHeader#91]
Hi Team,
I'm using datatables to display the dynamic data.The data is sent from another page in <th>,<td> format and is updated to table using innerHTML. Now I need to fix the headers and first two columns.I used  options but those didn't affect. Can anyone help me to achieve this.

Here's the code:
 $.get("emailpdata.jsp', function(data1){
            var divtable=document.getElementById('example');
               var xyz=data1;   
              divtable.innerHTML=xyz;
       }); 

I tried to provide options  after innerHtml but its not working. Thank you in advance.

**Comment by DataTables** [comment]
There is no option to fix both headers and columns in DataTables and FixedHeader at the moment. See #7.

**Comment by deepabagewadi** [comment]
If you see the example its possible. I want to achieve  similar to that. Because my data is updated dynamically the code in the link is not working.
Link for the example:
https://datatables.net/extensions/fixedcolumns/examples/styling/rowspan.html

**Comment by DataTables** [comment]
That's FixedColumns and does not use FixedHeader at all (this is the FixedHeader repo).

If you are having problems with your code, but the example is working, please post a link to your page by opening a support request in the [DataTables forums](//datatables.net/forums) as requested in the "new issue" text.
