### ISSUE TITLE
Calculate positions on scroll

### ISSUE THREAD

**Issue by mcgiany** [DataTables/FixedHeader#92]
Hi,

In case that table has dynamic rows (for example: expanded detail row), so the table height can change dynamicaly, it is necessary to calculate positions on every scroll. If not, then can the floating header disappear when you scroll the bigger table as were at init time.

My suggestion is to change code in constructor from this:
```
$(window)
			.on('scroll' + this.s.namespace, function () {
				that._scroll();
			} )
			.on( 'resize'+this.s.namespace, function () {
				that.s.position.windowHeight = $(window).height();
				that.update();
			} );
```
to this:
```
$(window)
			.on('scroll' + this.s.namespace, function () {
			    that._positions();
				that._scroll();
			} )
			.on( 'resize'+this.s.namespace, function () {
				that.s.position.windowHeight = $(window).height();
				that.update();
			} );
```

Or better, this behaviour can be changed by some options.

**Comment by DataTables** [comment]
Thanks for raising this. The problem with calling `_positions()` in the scroll event handler is that it is _very_ slow. It has to read measurements from the DOM, which is going to seriously impact performance.

I think it would be better to call the `fixedHeader.adjust()` public API method whenever the table's content changes.

**Comment by mcgiany** [comment]
Great. That helps me a lot. Thanks :)
