### ISSUE TITLE
     FixedColumns with styling "Complex headers", when zoom out brower, the fixed columns can not automatic adapt the table.

### ISSUE THREAD

**Issue by ukoyi** [DataTables/FixedHeader#99]
Hi Team,
     I'm using "FixedColumns" to fix colunms and fix  multiple rows in the table header, when zoom out browser, the fixed columns can not automatic adapt the table.   
 Link for the example:[https://datatables.net/extensions/fixedcolumns/examples/styling/rowspan.html]( https://datatables.net/extensions/fixedcolumns/examples/styling/rowspan.html)
Thanks for your help。

**Comment by DataTables** [comment]
Correct. If you search the forum you'll find a few threads about this. Unfortunately we don't support browser zoom at the moment for FixedHeader (or scrolling in general) as we've not yet found a way to reliably make this work. Sorry.

**Comment by ukoyi** [comment]
thank you
